### ISSUE TITLE
What about root

### ISSUE THREAD

**Issue by EpsilonKu** [Yohannfra/Vim-Vim-Project#1]
What about to add command that go to project root like https://github.com/airblade/vim-rooter .

**Comment by Yohannfra** [comment]
I don't understand what you'd want.

In the vim-rooter README there is this part
<img width="885" alt="Capture d’écran 2021-04-09 à 19 41 46" src="https://user-images.githubusercontent.com/36271388/114219934-a133a980-996b-11eb-8c94-98122ae0ccea.png">

You could then just use vim-rooter and vim-vim-Project together and do something like
```vim
let g:rooter_patterns = ['.vimproject']
```

**Comment by EpsilonKu** [comment]
ok
